wandb_version: 1

_jit_bailout_depth:
  desc: null
  value: 2
_jit_fusion_strategy:
  desc: null
  value:
  - - DYNAMIC
    - 3
root:
  desc: null
  value: results/toluene
run_name:
  desc: null
  value: example-run-toluene
wandb:
  desc: null
  value: true
wandb_project:
  desc: null
  value: toluene-example
model_builders:
  desc: null
  value:
  - SimpleIrrepsConfig
  - EnergyModel
  - PerSpeciesRescale
  - ForceOutput
  - RescaleEnergyEtc
dataset_statistics_stride:
  desc: null
  value: 1
default_dtype:
  desc: null
  value: float32
allow_tf32:
  desc: null
  value: false
verbose:
  desc: null
  value: info
model_debug_mode:
  desc: null
  value: false
equivariance_test:
  desc: null
  value: false
grad_anomaly_mode:
  desc: null
  value: false
append:
  desc: null
  value: true
seed:
  desc: null
  value: 123
dataset_seed:
  desc: null
  value: 456
r_max:
  desc: null
  value: 4.0
num_layers:
  desc: null
  value: 4
l_max:
  desc: null
  value: 2
parity:
  desc: null
  value: true
num_features:
  desc: null
  value: 32
nonlinearity_type:
  desc: null
  value: gate
nonlinearity_scalars:
  desc: null
  value:
    e: silu
    o: tanh
nonlinearity_gates:
  desc: null
  value:
    e: silu
    o: tanh
num_basis:
  desc: null
  value: 8
BesselBasis_trainable:
  desc: null
  value: true
PolynomialCutoff_p:
  desc: null
  value: 6
invariant_layers:
  desc: null
  value: 2
invariant_neurons:
  desc: null
  value: 64
avg_num_neighbors:
  desc: null
  value: auto
use_sc:
  desc: null
  value: true
dataset:
  desc: null
  value: npz
dataset_url:
  desc: null
  value: http://quantum-machine.org/gdml/data/npz/toluene_ccsd_t.zip
dataset_file_name:
  desc: null
  value: ./benchmark_data/toluene_ccsd_t-train.npz
key_mapping:
  desc: null
  value:
    z: atomic_numbers
    E: total_energy
    F: forces
    R: pos
npz_fixed_field_keys:
  desc: null
  value:
  - atomic_numbers
chemical_symbols:
  desc: null
  value:
  - H
  - C
log_batch_freq:
  desc: null
  value: 10
log_epoch_freq:
  desc: null
  value: 1
save_checkpoint_freq:
  desc: null
  value: -1
save_ema_checkpoint_freq:
  desc: null
  value: -1
n_train:
  desc: null
  value: 100
n_val:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.005
batch_size:
  desc: null
  value: 5
validation_batch_size:
  desc: null
  value: 10
max_epochs:
  desc: null
  value: 100000
train_val_split:
  desc: null
  value: random
shuffle:
  desc: null
  value: true
metrics_key:
  desc: null
  value: validation_loss
use_ema:
  desc: null
  value: true
ema_decay:
  desc: null
  value: 0.99
ema_use_num_updates:
  desc: null
  value: true
report_init_validation:
  desc: null
  value: true
early_stopping_patiences:
  desc: null
  value:
    validation_loss: 50
early_stopping_lower_bounds:
  desc: null
  value:
    LR: 1.0e-05
loss_coeffs:
  desc: null
  value:
    forces: 1
    total_energy:
    - 1
    - PerAtomMSELoss
metrics_components:
  desc: null
  value:
  - - forces
    - mae
  - - forces
    - rmse
  - - forces
    - mae
    - PerSpecies: true
      report_per_component: false
  - - forces
    - rmse
    - PerSpecies: true
      report_per_component: false
  - - total_energy
    - mae
  - - total_energy
    - mae
    - PerAtom: true
optimizer_name:
  desc: null
  value: Adam
optimizer_amsgrad:
  desc: null
  value: true
lr_scheduler_name:
  desc: null
  value: ReduceLROnPlateau
lr_scheduler_patience:
  desc: null
  value: 100
lr_scheduler_factor:
  desc: null
  value: 0.5
per_species_rescale_shifts_trainable:
  desc: null
  value: false
per_species_rescale_scales_trainable:
  desc: null
  value: false
per_species_rescale_shifts:
  desc: null
  value: dataset_per_atom_total_energy_mean
per_species_rescale_scales:
  desc: null
  value: dataset_forces_rms
torch_version:
  desc: null
  value: 1.12.0+cu102
e3nn_version:
  desc: null
  value: 0.5.1
nequip_version:
  desc: null
  value: 0.5.6
code_commits:
  desc: null
  value:
    nequip: 4e2a46ad957cb0acd679e8f6b249751ffd9b4fa3
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716897919.081851
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 55
      - 105
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.9.17
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
num_weights:
  desc: null
  value: 363096
