#!/usr/bin/env python
"""Regenerate workflows/notebooks/INDEX.md from the notebooks themselves.

Grouping is by CAPABILITY, because that is how someone looks for an example --
"is there one that does surfaces?" -- not by the order things happened to get
written. The numbers stay as they are: they are immutable identifiers, cited in
commit messages, memory files and open tasks, and renumbering would break every
one of those plus `git log --follow`.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

NB = Path(__file__).resolve().parents[1] / "notebooks"

GROUPS = [
    ("Wannierisation itself", "how the localisation is done, and with what",
     [4, 5]),
    ("Surfaces and interfaces", "spectral functions of semi-infinite and slab "
     "geometries, ARPES", [1, 2, 3, 14, 15, 25, 26]),
    ("Bands, Berry curvature, transport", "effective masses, anomalous and spin "
     "Hall, spin accumulation", [6, 7, 8, 9, 12]),
    ("Phonons and electron-phonon", "alpha^2F, resistivity, band renormalisation",
     [10, 11, 13, 16, 24, 28]),
    ("Superconductivity", "Tc models, penetration depth, superfluid weight",
     [20, 21, 22, 29]),
    ("Magnetism", "exchange couplings and magnons", [17, 23]),
    ("Other electronic-structure codes", "waw on something that is not QE",
     [18, 19]),
    ("Correlated electrons", "DMFT", [27]),
]


def title_of(p: Path) -> str:
    nb = json.loads(p.read_text())
    for c in nb["cells"]:
        if c["cell_type"] == "markdown":
            first = "".join(c["source"]).strip().splitlines()[0]
            return re.sub(r"^#+\s*|^\d+\s*[-—]\s*", "", first).strip()
    return p.stem


def runs_of(p: Path) -> list[str]:
    src = "".join("".join(c["source"]) for c in json.loads(p.read_text())["cells"]
                  if c["cell_type"] == "code")
    return sorted(set(re.findall(r"['\"]runs['\"]\s*/\s*['\"]([\w.-]+)['\"]", src)
                      + re.findall(r"runs/([\w.-]+)", src)))


def main() -> int:
    books = {int(re.match(r"(\d+)", p.stem).group(1)): p
             for p in sorted(NB.glob("[0-9]*.ipynb"))
             if re.match(r"\d+", p.stem)}
    listed = {n for _, _, ns in GROUPS for n in ns}
    out = ["# Notebook index", "",
           "Generated by `workflows/scripts/make_index.py` -- edit the grouping "
           "there, not here.", "",
           "Numbers are permanent identifiers and are never reused or "
           "reassigned; the grouping below is the only thing that moves.", ""]
    for name, blurb, nums in GROUPS:
        out += [f"## {name}", f"*{blurb}*", ""]
        for n in nums:
            p = books.get(n)
            if p is None:
                continue
            r = runs_of(p)
            out.append(f"- **{n:02d}** [{title_of(p)}]({p.name})"
                       + (f"  \n  <sub>runs: {', '.join(r)}</sub>" if r else ""))
        out.append("")
    missing = sorted(set(books) - listed)
    if missing:
        out += ["## Not yet grouped", ""]
        out += [f"- **{n:02d}** [{title_of(books[n])}]({books[n].name})"
                for n in missing] + [""]
    (NB / "INDEX.md").write_text("\n".join(out))
    print(f"wrote {NB/'INDEX.md'}: {len(books)} notebooks, "
          f"{len(missing)} ungrouped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
