"""
End-to-end scf -> native .nnkp -> nscf -> pw2wannier90 overlap generation.

The Wannier neighbour topology (``.nnkp``) is generated by waw itself
(``waw.core.generate_nnkp`` + ``waw.interfaces.wannier90.io.write_nnkp``);
the only wannier90-ecosystem binary used is QE's ``pw2wannier90.x``, which
writes the code-agnostic ``.mmn/.amn/.eig`` overlaps. No ``wannier90.x``
and no ``.win``/``.chk``.
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np

from waw.core import generate_nnkp
from waw.interfaces.wannier90.io import (
    write_nnkp, read_mmn, read_amn, read_eig, read_spn, read_uHu, read_dmn,
    read_sHu, read_sIu, write_sym,
)
from waw.interfaces.ase.structure import monkhorst_pack, real_lattice, recip_lattice
from waw.units import BOHR_TO_ANG

from .io import (
    write_pw_input, run_pw, run_pw2wannier90, read_fermi_energy,
    gamma_only_half_shell_nnkp,
)


def _jsonable(x):
    """Anything -> a stable, comparable JSON value."""
    if isinstance(x, np.ndarray):
        return _jsonable(x.tolist())
    if isinstance(x, (np.integer, np.floating)):
        return x.item()
    if isinstance(x, dict):
        return {str(k): _jsonable(v) for k, v in sorted(x.items(), key=lambda kv: str(kv[0]))}
    if isinstance(x, (list, tuple)):
        return [_jsonable(v) for v in x]
    if isinstance(x, Path):
        return str(x)
    return x


# Which stage each recorded setting invalidates. Anything in NSCF_KEYS changes
# the wavefunctions, so both stages have to rerun; everything else only changes
# what pw2wannier90 makes of wavefunctions that are still valid.
NSCF_KEYS = ("cell", "positions", "species", "mp_grid", "nbnd", "ecutwfc",
             "gamma_only", "nscf_symmetry", "nscf_electrons", "system_extra",
             "hubbard", "hubbard_projector")


def _overlap_fingerprint(*, atoms, **kw) -> dict:
    """Everything the .nnkp/.amn/.mmn/.eig on disk depend on, JSON-comparable."""
    fp = {"cell": np.round(np.asarray(atoms.cell[:]), 10),
          "positions": np.round(atoms.get_scaled_positions(), 10),
          "species": list(atoms.get_chemical_symbols())}
    fp.update(kw)
    return _jsonable(fp)


def _fingerprint_verdict(path: Path, fp_now: dict, files_present: bool):
    """(stale_nscf, stale_overlaps) against the recorded fingerprint.

    A missing record means a run predating this check, so staleness cannot be
    established either way -- that is warned about rather than guessed at, and
    the current fingerprint is written so the NEXT change is caught.
    """
    if not files_present:
        return False, False                      # everything reruns anyway
    if not path.exists():
        warnings.warn(
            f"reusing the overlaps in {path.parent} but {path.name} is absent, "
            f"so it cannot be checked that they were made with the settings "
            f"passed now. If `projections`, `num_wann`, `exclude_bands` or the "
            f"scdm/atom_proj settings have changed since they were written, the "
            f"reused .amn is stale and the resulting model is built on the old "
            f"projections. Delete {path.parent}/*.amn (or pass rerun_nscf=True) "
            f"if in doubt; from now on this is detected automatically.",
            RuntimeWarning, stacklevel=3)
        return False, False
    try:
        old = json.loads(path.read_text())
    except (OSError, ValueError):
        return True, True
    changed = [k for k in set(old) | set(fp_now) if old.get(k) != fp_now.get(k)]
    if not changed:
        return False, False
    nscf = sorted(k for k in changed if k in NSCF_KEYS)
    other = sorted(k for k in changed if k not in NSCF_KEYS)
    what = ", ".join(nscf + other)
    print(f"  [generate_overlaps] settings changed since the files in "
          f"{path.parent} were written ({what}); rerunning "
          f"{'NSCF + pw2wannier90' if nscf else 'pw2wannier90 only'}",
          flush=True)
    return bool(nscf), True


def generate_overlaps(
    atoms, mp_grid, workdir, seedname, *,
    ecutwfc: float,
    scf_kpts,
    nbnd: int,
    pseudopotentials: dict,
    pseudo_dir,
    num_wann: int,
    exclude_bands=(),
    scdm_mu: float | None = None,
    scdm_sigma: float | None = None,
    scdm_entanglement: str = "isolated",
    system_extra: dict | None = None,
    scf_electrons: dict | None = None,
    nscf_electrons: dict | None = None,
    hubbard: dict | None = None,
    hubbard_projector: str = "ortho-atomic",
    ncores: int = 16,
    write_spn: bool = False,
    write_unk: bool = False,
    write_uHu: bool = False,
    write_sHu: bool = False,
    write_sIu: bool = False,
    write_dmn: bool = False,
    nscf_symmetry: bool = False,
    rerun_scf: bool = True,
    rerun_nscf: bool = True,
    gamma_only: bool = False,
    projections=None,
    atom_proj: bool = False,
    atom_proj_ext: bool = False,
    atom_proj_dir: str | Path | None = None,
    atom_proj_exclude=(),
    spin_component: str | None = None,
    sym_ops: tuple[np.ndarray, np.ndarray] | None = None,
) -> dict:
    """
    Full converged scf -> native .nnkp -> nscf -> pw2wannier90(SCDM) pipeline,
    returning the loaded overlap arrays ready for
    ``waw.interfaces.ase.driver.wannierize``.

    Returns a dict with keys: kpts, mmn, amn, eig, nnkpts, g_vectors,
    fermi_energy (eV, from the SCF) (+ spn if write_spn). By default uses
    SCDM projections (``scdm_proj=.true.``, no analytic projection block
    needed, works for noncollinear/spinor cases too); ``scdm_entanglement``
    is 'isolated' | 'erfc' | 'gaussian', with mu/sigma in eV for the
    entangled variants.

    ``exclude_bands`` (1-based) drops bands from the Wannierisation, e.g. for
    PseudoDojo pseudos carrying semicore states. The NSCF pads ``nbnd`` with
    a few empty conduction bands beyond the highest kept band so Davidson
    converges cleanly; override via ``nscf_electrons``. ``rerun_scf=False``
    reuses a completed SCF in ``out/``.

    ``scf_electrons`` overrides the SCF ``&electrons`` namelist (default
    ``{"conv_thr": 1e-10}``) -- e.g. ``{"mixing_mode": "local-TF",
    "mixing_beta": 0.2, "conv_thr": 1e-9}`` to converge a hard magnetic-metal
    SCF that would otherwise stall on the default charge mixing.

    ``hubbard`` / ``hubbard_projector``: DFT+U via the ``HUBBARD`` card, passed
    to both the SCF and NSCF (see ``write_pw_input``); e.g.
    ``hubbard={"Ni-3d": 3.24}`` puts U=3.24 eV on every Ni 3d manifold.

    ``rerun_nscf=False`` similarly reuses a completed NSCF + pw2wannier90
    pair (both being the expensive steps for a dense Wannier mesh) -- skips
    both only when the NSCF/pw2wannier90 ``JOB DONE`` markers AND every
    output file this call will actually read back (``.mmn``/``.amn``/
    ``.eig``, plus ``.spn``/``.uHu``/``.sHu``/``.sIu``/``.dmn`` if
    ``write_spn``/``write_uHu``/``write_sHu``/``write_sIu``/``write_dmn``
    are set) already exist in ``workdir`` -- changing ``write_spn``/etc.
    on a later call with the same ``workdir`` correctly forces a rerun
    rather than silently reading a stale/missing file. Independent of
    ``rerun_scf`` (either can be reused without the other).

    ``write_sHu``/``write_sIu``: the two extra ab-initio quantities the
    spin Hall conductivity Ryoo method needs (`analysis.spin_hall`'s
    `build_shc_ryoo_operators`) -- genuine ab-initio matrix elements one
    neighbour-shell away, not an approximation reconstructed from
    ``.mmn``+``.spn`` (that's what the alternative Qiao method already is).
    Needs ``noncolin=.true.`` (System namelist) like ``write_spn``/
    ``write_uHu``; QE's ``pw2wannier90.x`` computes these in eV internally
    for ``sHu`` (``* rytoev``) -- convert with ``EV_TO_HARTREE`` before
    passing to ``build_shc_ryoo_operators``, matching how ``.uHu`` is
    handled.

    ``gamma_only=True`` is for isolated molecules: ``mp_grid`` is forced to
    ``(1,1,1)`` and scf/nscf use QE's ``K_POINTS {gamma}`` real-wavefunction
    trick (``scf_kpts`` then ignored). pw2wannier90 doesn't support SCDM for
    gamma-only wavefunctions, so this requires explicit analytic
    ``projections`` instead.

    ``projections`` (optional): analytic projection specs as accepted by
    `write_nnkp`'s ``projections=`` -- when given, used instead of SCDM
    (``scdm_entanglement`` then ignored).

    ``atom_proj`` (optional): builds the .amn from the pseudopotential's own
    atomic pseudo-orbitals (pw2wannier90 ``atom_proj=.true.``) instead of
    SCDM or analytic projections -- pairs with projectability-based
    disentanglement (``proj_min``/``proj_max`` in
    ``waw.core.disentangle.disentangle``). Mutually exclusive with
    ``projections``; ``scdm_entanglement``/mu/sigma ignored when set.

    ``atom_proj_ext`` (optional): pw2wannier90's ``atom_proj_ext=.true.`` --
    reads atomic projector radial functions from a plain-text file per
    species in ``atom_proj_dir`` instead of the pseudopotential's embedded
    ``PP_PSWFC`` block (see
    ``waw.interfaces.quantum_espresso.upf.write_atom_proj_ext`` to build that
    directory). Implies ``atom_proj=True``; ``atom_proj_exclude`` (1-based
    projector indices) drops specific channels.

    ``write_dmn``/``nscf_symmetry`` (symmetry-adapted Wannier functions --
    ``waw.core.sitesym``): ``write_dmn=True`` asks pw2wannier90 for the
    ``.dmn`` symmetry file. Needs an explicit ``projections`` block (SCDM's
    implicit sites can't be resolved against the symmetry group), and the
    NSCF must see the crystal's point-group symmetry, so pass
    ``nscf_symmetry=True`` to turn off this function's usual
    ``nosym=.true., noinv=.true.`` (safe: the NSCF's explicit ``K_POINTS
    crystal`` list can't be reduced/reordered regardless of symmetry).

    ``sym_ops`` (optional): ``(rotations, translations)`` -- ``rotations``
    (n, 3, 3), ``translations`` (n, 3), crystal/fractional coordinates.
    Writes ``<seedname>.sym`` and passes pw2wannier90 ``read_sym=.true.``,
    overriding its symmetry auto-detection with this explicit operation
    list. Needed whenever an analytic projection site is a fixed point of
    only a subgroup of the crystal's full symmetry (e.g. a tetrahedral-hole
    site with no inversion), otherwise ``write_dmn`` would build a ``.dmn``
    for the wrong, too-large symmetry group.

    ``spin_component`` (optional, ``'up'`` | ``'down'``): for a collinear
    spin-polarized run (QE ``nspin=2`` in ``system_extra``), pw2wannier90
    needs one run per spin channel -- pass a distinct ``seedname`` per call
    (e.g. ``'fe_up'``/``'fe_dn'``), with ``spin_component`` selecting which
    channel pw2wannier90 writes. Unrelated to the noncollinear/SOC
    ``spinor`` path (one run, both spin components already mixed).
    """
    workdir = Path(workdir)
    (workdir / "out").mkdir(parents=True, exist_ok=True)
    system_extra = dict(system_extra or {})
    exclude_bands = list(exclude_bands)
    if gamma_only:
        mp_grid = (1, 1, 1)
        kpts = np.zeros((1, 3))
    else:
        kpts = monkhorst_pack(mp_grid)

    common_system = {"ecutwfc": ecutwfc, **system_extra}

    # 1. SCF (dense mesh)
    scf_done = (workdir / f"{seedname}.scf.out").exists() and \
        "JOB DONE" in (workdir / f"{seedname}.scf.out").read_text()
    if rerun_scf or not scf_done:
        write_pw_input(
            workdir / f"{seedname}.scf.in", atoms,
            control={"calculation": "scf", "prefix": seedname,
                     "outdir": "./out", "pseudo_dir": str(pseudo_dir)},
            system=common_system,
            electrons={"conv_thr": 1.0e-10, **(scf_electrons or {})},
            pseudopotentials=pseudopotentials,
            kpoints=("gamma",) if gamma_only else ("automatic", tuple(scf_kpts), (0, 0, 0)),
            hubbard=hubbard, hubbard_projector=hubbard_projector,
        )
        run_pw(workdir / f"{seedname}.scf.in", workdir / f"{seedname}.scf.out", ncores=ncores)

    # 2. .nnkp, generated by waw. Noncollinear/spin-orbit runs need a
    #    spinor_projections block; detect from the system namelist.
    spinors = bool(system_extra.get("noncolin") or system_extra.get("lspinorb"))
    nnkp = gamma_only_half_shell_nnkp() if gamma_only else generate_nnkp(kpts, recip_lattice(atoms), mp_grid)
    write_nnkp(
        workdir / f"{seedname}.nnkp",
        real_lattice=real_lattice(atoms) * BOHR_TO_ANG,
        recip_lattice=recip_lattice(atoms) / BOHR_TO_ANG,
        kpoints=kpts, nnkpts=nnkp["nnkpts"], g_vectors=nnkp["g_vectors"],
        projections=projections,
        auto_projections=None if projections else num_wann,   # scdm_proj=.true. requires this block
        exclude_bands=exclude_bands,
        spinors=spinors,
    )

    # 3+4. NSCF on the Wannier mesh + pw2wannier90 -> overlaps. Both are
    # gated together by `rerun_nscf` (skipping one without the other would
    # leave pw2wannier90 reading a stale/mismatched NSCF wavefunction).
    needed_files = [workdir / f"{seedname}.{ext}" for ext in ("mmn", "amn", "eig")]
    if write_spn:
        needed_files.append(workdir / f"{seedname}.spn")
    if write_uHu:
        needed_files.append(workdir / f"{seedname}.uHu")
    if write_sHu:
        needed_files.append(workdir / f"{seedname}.sHu")
    if write_sIu:
        needed_files.append(workdir / f"{seedname}.sIu")
    if write_dmn:
        needed_files.append(workdir / f"{seedname}.dmn")

    def _job_done(out_file: Path) -> bool:
        return out_file.exists() and "JOB DONE" in out_file.read_text()

    nscf_pw2wan_done = (
        _job_done(workdir / f"{seedname}.nscf.out")
        and _job_done(workdir / f"{seedname}.pw2wan.out")
        and all(f.exists() for f in needed_files)
    )

    # Which of the two stages the settings in hand actually invalidate. Without
    # this, "the files exist and both jobs said JOB DONE" is the whole gate, so
    # changing `projections` and rerunning in the same directory rewrites the
    # .nnkp (step 2, unconditional) and then reuses the OLD .amn against it:
    # a model built on projections nobody asked for, with nothing printed.
    # `_check_overlap_block_order` does not catch it -- it validates the
    # neighbour block order, which the projections do not touch.
    fp_now = _overlap_fingerprint(
        atoms=atoms, mp_grid=mp_grid, nbnd=nbnd, ecutwfc=ecutwfc,
        exclude_bands=exclude_bands, num_wann=num_wann,
        projections=projections, spinors=spinors, gamma_only=gamma_only,
        nscf_symmetry=nscf_symmetry, nscf_electrons=nscf_electrons,
        system_extra=system_extra, hubbard=hubbard,
        hubbard_projector=hubbard_projector, atom_proj=atom_proj,
        atom_proj_ext=atom_proj_ext, atom_proj_dir=atom_proj_dir,
        atom_proj_exclude=atom_proj_exclude, scdm_entanglement=scdm_entanglement,
        scdm_mu=scdm_mu, scdm_sigma=scdm_sigma, spin_component=spin_component,
        sym_ops=sym_ops, write_flags=dict(
            spn=write_spn, unk=write_unk, uHu=write_uHu, sHu=write_sHu,
            sIu=write_sIu, dmn=write_dmn),
    )
    # `nscf_pw2wan_done and not rerun_nscf` -- the question is whether the files
    # on disk are about to be REUSED, not merely whether they exist. Asking only
    # whether they exist made the "provenance absent, cannot check" warning fire
    # on every rerun_nscf=True call in a directory that already had a run, where
    # nothing is being reused and there is nothing to be uncertain about.
    stale_nscf, stale_overlaps = _fingerprint_verdict(
        workdir / f"{seedname}.waw-provenance.json", fp_now,
        nscf_pw2wan_done and not rerun_nscf)

    run_nscf = rerun_nscf or not nscf_pw2wan_done or stale_nscf
    if run_nscf:
        # 3. NSCF on the Wannier mesh (explicit crystal card), with
        #    conduction bands. `nbnd` must carry a buffer beyond the
        #    highest band kept, or Davidson stalls on the boundary band.
        #    Override via `nscf_electrons`.
        nscf_elec = {"conv_thr": 1.0e-8, "diago_thr_init": 1.0e-4,
                     **(nscf_electrons or {})}
        write_pw_input(
            workdir / f"{seedname}.nscf.in", atoms,
            control={"calculation": "nscf", "prefix": seedname,
                     "outdir": "./out", "pseudo_dir": str(pseudo_dir)},
            system={**common_system, "nbnd": nbnd,
                   **({} if nscf_symmetry else {"nosym": True, "noinv": True})},
            electrons=nscf_elec,
            pseudopotentials=pseudopotentials,
            kpoints=("gamma",) if gamma_only else ("crystal", kpts),
            hubbard=hubbard, hubbard_projector=hubbard_projector,
        )
        run_pw(workdir / f"{seedname}.nscf.in", workdir / f"{seedname}.nscf.out", ncores=ncores)

    # 4. pw2wannier90 (SCDM, analytic projections, or atom_proj) -> overlaps.
    #    Runs whenever the NSCF just ran, and ALSO on its own when only the
    #    overlap-side settings changed (projections, scdm, atom_proj, which
    #    extra matrices to write): those do not touch the NSCF, whose
    #    wavefunctions in ./out stay valid, so there is no reason to pay for it
    #    again -- but the .amn must not be left stale either.
    if run_nscf or stale_overlaps:
        if projections:
            scdm = {}
        elif atom_proj or atom_proj_ext:
            scdm = {"atom_proj": True}
            if atom_proj_ext:
                scdm["atom_proj_ext"] = True
                scdm["atom_proj_dir"] = str(atom_proj_dir)
                if atom_proj_exclude:
                    scdm["atom_proj_exclude"] = list(atom_proj_exclude)
        else:
            scdm = {"scdm_proj": True, "scdm_entanglement": scdm_entanglement}
            if scdm_entanglement != "isolated":
                scdm["scdm_mu"] = scdm_mu
                scdm["scdm_sigma"] = scdm_sigma
        inp = {
            "outdir": "./out", "prefix": seedname, "seedname": seedname,
            "write_mmn": True, "write_amn": True, "write_eig": True,
            "write_unk": write_unk, "write_spn": write_spn, "write_uHu": write_uHu,
            "write_sHu": write_sHu, "write_sIu": write_sIu,
            "write_dmn": write_dmn, **scdm,
        }
        if spin_component is not None:
            inp["spin_component"] = spin_component
        if sym_ops is not None:
            rotations, translations = sym_ops
            write_sym(workdir / f"{seedname}.sym", rotations, translations)
            inp["read_sym"] = True
        run_pw2wannier90(workdir, seedname, inp, ncores=min(ncores, 4))

    mmn, _kpb = read_mmn(workdir / f"{seedname}.mmn")
    _check_overlap_block_order(_kpb, nnkp, workdir, seedname)
    # Only now that the files have been read back successfully: a fingerprint
    # written before that could vouch for a half-finished run.
    (workdir / f"{seedname}.waw-provenance.json").write_text(
        json.dumps(fp_now, indent=1, sort_keys=True))
    out = {
        "kpts": kpts,
        "mmn": mmn,
        "amn": read_amn(workdir / f"{seedname}.amn"),
        "eig": read_eig(workdir / f"{seedname}.eig"),
        "nnkpts": nnkp["nnkpts"],
        "g_vectors": nnkp["g_vectors"],
        "fermi_energy": read_fermi_energy(workdir / f"{seedname}.scf.out"),   # eV
    }
    if write_spn:
        out["spn"] = read_spn(workdir / f"{seedname}.spn")["spn"]
    if write_sHu:
        out["sHu"] = read_sHu(workdir / f"{seedname}.sHu")["data"]
    if write_sIu:
        out["sIu"] = read_sIu(workdir / f"{seedname}.sIu")["data"]
    if write_uHu:
        out["uHu"] = read_uHu(workdir / f"{seedname}.uHu")["uHu"]
    if write_dmn:
        out["dmn"] = read_dmn(workdir / f"{seedname}.dmn", num_wann=num_wann)
    return out


def _check_overlap_block_order(kpb_map, nnkp, workdir, seedname) -> None:
    """Verify the ``.mmn`` block order matches the ``.nnkp`` we just wrote.

    Every consumer here pairs overlap block ``p`` with neighbour ``p`` of the
    ``.nnkp`` (``bvecs[k, p]``, ``kb_idx[k, p]``). ``pw2wannier90`` honours
    that because it loops over the ``.nnkp``'s own neighbour list -- but the
    pairing is an ASSUMPTION, and a wrong one corrupts results silently:
    ``AA_R``/``BB_R`` are single sums and stay invariant under a *consistent*
    permutation, so bands and even the AHC can look perfect while
    neighbour-PAIR quantities (``CC_R`` from ``.uHu``, ``QQ_R`` from ``.sIu``)
    are scrambled.

    The realistic way to break it is a stale cache: ``rerun_nscf=False``
    rewrites the ``.nnkp`` but reuses the overlap files, so if the neighbour
    ordering ever shifts (code change, different ASE/symmetry result) the two
    silently disagree. ``.uHu``/``.uIu``/``.sIu`` carry no block labels and
    cannot be checked at all -- but they come from the SAME pw2wannier90 run
    as the ``.mmn``, so the ``.mmn``'s labels are the canary for the whole set.

    Raises with an actionable message rather than reordering: reordering the
    ``.mmn`` alone would desync it from the unlabelled files.

    (Found the hard way 2026-07-29: postw90 mispairs waw-ordered ``.uHu``
    blocks against its own regenerated neighbour list -- see
    ``waw/analysis/orbital_magnetization.py``.)
    """
    from ..ase.driver import nnkp_from_kpb_map

    if not kpb_map:          # reader supplied no labels (or a test stub): nothing to check
        return
    nnkpts, g_vectors = nnkp["nnkpts"], nnkp["g_vectors"]
    nk, nnb = nnkpts.shape
    if len(kpb_map) != nk * nnb:
        raise ValueError(
            f"{workdir / (seedname + '.mmn')}: has {len(kpb_map)} blocks but the "
            f".nnkp expects {nk * nnb} ({nk} k-points x {nnb} neighbours). The "
            f"cached overlaps do not match this run -- delete "
            f"{seedname}.mmn/.amn/.eig (and any .uHu/.uIu/.spn/.sIu/.sHu) or "
            f"pass rerun_nscf=True."
        )
    file_nnkpts, file_g = nnkp_from_kpb_map(kpb_map, nk, nnb)
    if not (np.array_equal(file_nnkpts, nnkpts) and np.array_equal(file_g, g_vectors)):
        bad = int(np.argmax((file_nnkpts != nnkpts).any(axis=1)))
        raise ValueError(
            f"{workdir / (seedname + '.mmn')}: neighbour block order disagrees with "
            f"{seedname}.nnkp (first mismatch at k-point {bad}: file has "
            f"{file_nnkpts[bad].tolist()}, .nnkp has {nnkpts[bad].tolist()}). "
            f"Every overlap would be paired with the wrong b-vector, silently "
            f"corrupting CC_R/QQ_R (and thus orbital magnetization, gyrotropic "
            f"K_orb and the SAC) while leaving bands and the AHC looking fine. "
            f"This normally means cached overlaps were written against a "
            f"different .nnkp: delete {seedname}.mmn/.amn/.eig plus any "
            f".uHu/.uIu/.spn/.sIu/.sHu, or pass rerun_nscf=True."
        )
