"""
XCrySDen Band-XCRYSDEN-Structure-File (.bxsf) export, for Fermi-surface
visualization in XCrySDen.

Reproduces Wannier90's `fermi_surface_plot = .true.`: interpolated bands
on a closed (N+1)^3 k-grid, k_i = m/N for m = 0..N inclusive at both
ends, since XCrySDen's isosurface renderer needs the repeated boundary
point to interpolate across cell edges (unlike a Monkhorst-Pack mesh,
which excludes that periodic image). This differs from
`waw.analysis.fermi_surface.fermi_surface_sheets`, which uses the
half-open `[0,1)^3` periodic mesh since marching_cubes wraps the volume
itself.

File format is eV / Angstrom^-1 (unlike the rest of `waw`'s atomic-units
convention); this module is the conversion boundary.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from ...core.hamiltonian import HamiltonianR, interpolate_bands
from ...units import BOHR_TO_ANG, HARTREE_TO_EV


def fermi_surface_kgrid(num_points: int) -> np.ndarray:
    """
    Closed (num_points+1)^3 k-grid in crystal coordinates, k_i = m/num_points
    for m = 0..num_points. Flattened in the same order as Wannier90's
    nested loops (x slowest, z fastest) so it lines up with write_bxsf's
    band-value ordering.
    """
    idx = np.arange(num_points + 1)
    X, Y, Z = np.meshgrid(idx, idx, idx, indexing="ij")
    return np.stack([X, Y, Z], axis=-1).reshape(-1, 3) / num_points


def write_bxsf(
    path: str | Path,
    bands: np.ndarray,
    fermi_energy: float,
    recip_lattice: np.ndarray,
    num_points: int,
    header: str = "written by waw",
) -> None:
    """
    Write a .bxsf file (XCrySDen Fermi-surface format).

    Args:
      bands        : ((num_points+1)^3, nw) float64 eV, in
                     fermi_surface_kgrid's flatten order (x slowest, z
                     fastest); i.e. exactly interpolate_bands(hr,
                     fermi_surface_kgrid(num_points)) * HARTREE_TO_EV.
      fermi_energy : eV
      recip_lattice: (3, 3) rows = b1,b2,b3, in Angstrom^-1 (.bxsf's own
                     convention).
      num_points   : the N in the (N+1)^3 grid (fermi_surface_kgrid(N)).
    """
    npts_plot, nw = bands.shape
    n1 = num_points + 1

    lines = [
        " BEGIN_INFO",
        "      #",
        "      # this is a Band-XCRYSDEN-Structure-File",
        "      # for Fermi Surface Visualisation",
        "      #",
        f"      # Generated by waw ({header})",
        "      #",
        f"      Fermi Energy: {fermi_energy:.8f}",
        " END_INFO",
        "",
        " BEGIN_BLOCK_BANDGRID_3D",
        "from_waw",
        " BEGIN_BANDGRID_3D_fermi",
        f"{nw}",
        f"{n1} {n1} {n1}",
        "0.0 0.0 0.0",
        *(f"{v[0]:.8f} {v[1]:.8f} {v[2]:.8f}" for v in recip_lattice),
    ]
    for i in range(nw):
        lines.append(f"BAND:  {i + 1}")
        lines.extend(f"{bands[k, i]:16.8E}" for k in range(npts_plot))
    lines += ["END_BANDGRID_3D", " END_BLOCK_BANDGRID_3D"]

    Path(path).write_text("\n".join(lines) + "\n")


def fermi_surface(
    hr:            HamiltonianR,
    recip_lattice: np.ndarray,
    fermi_energy:  float,
    path:          str | Path,
    num_points:    int = 50,
) -> None:
    """
    Interpolate bands on the closed (num_points+1)^3 grid and write a
    .bxsf file, in one call -- the waw equivalent of Wannier90's
    `fermi_surface_plot = .true.` + `fermi_energy = ...`.

    Args:
      hr           : HamiltonianR from waw.core.hamiltonian.compute_hr
      recip_lattice: (3, 3) rows = b1,b2,b3, in Bohr^-1 (waw's
                     usual convention, e.g. parse_recip_lattice's output)
                     -- converted internally to the Angstrom^-1 that
                     .bxsf expects.
      fermi_energy : Hartree (atomic units, like all `core`/`analysis`
                     inputs) -- converted internally to the eV that .bxsf
                     expects.
      num_points   : grid density (Wannier90's `fermi_surface_num_points`,
                     default there is also 50)
    """
    kpts = fermi_surface_kgrid(num_points)
    # Atomic units in; the .bxsf file format is eV / Angstrom^-1
    # (file-format boundary -- see module docstring).
    bands = interpolate_bands(hr, kpts) * HARTREE_TO_EV
    write_bxsf(path, bands, fermi_energy * HARTREE_TO_EV,
               recip_lattice / BOHR_TO_ANG, num_points)
